config/routes.rb
Rails.application.routes.draw do

  root to: 'flats#index'
  get 'flats/search'

  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks'}

  resources :flats do
    resources :bookings, except: [:destroy]
    resources :images, only: [:new, :create, :destroy]
  end

  resources :users, only: [:show]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, omniauth_providers: [:facebook]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :flats
  has_many :bookings


  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
      user.remote_picture_url = auth.info.image
    end
  end

  mount_uploader :picture, PictureUploader

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_path(@user.id), notice: 'user was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @flats = Flat.all.where(user_id: current_user.id)

  end

  def edit

  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'user was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :encrypted_password, :last_name, :first_name, :picture, :picture_cache)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>Update your profile</h2>

<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name, required: true, autofocus: true %>
    <%= f.input :last_name, required: true, autofocus: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Update" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<%= current_user.email %>

app/views/users/show.html.erb
<div class="container" style="margin-top: 40px; text-align: left">
  <div class="row">
    <div class="col-xs-2">
      <%= image_tag current_user.picture, class: "avatar-large" %>
    </div>
    <div class="col-xs-9">
      <p>Email: <%= current_user.email %> </p>
      <p>First name: <%= current_user.first_name %> </p>
      <p>Last name: <%= current_user.last_name %> </p>


      <%= link_to "Add New Hut", new_flat_path, :class=>"btn btn-default" %>
      <%= link_to "Edit Password", edit_user_registration_path, :class=>"btn btn-default" %>

      <h3>Your Huts</h3>
      <div style="padding: 0 500 0 0">
        <% @flats.each do |flat| %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= flat.images[0].photo if flat.images[0] != nil %>);">
          <div class="card-category"><%= flat.city %></div>
          <div class="card-description">
            <h2><%= flat.title %></h2>
            <p><%= flat.address %></p>

          </div>
          <%= link_to "", flat_path(flat), class: "card-link" %>
          <% if current_user == nil %>
          <% elsif flat.user.id == current_user.id %>
          <div class="card-edit" style="z-index:999;"><%= link_to ("<i class='fa fa-pencil'></i>").html_safe, edit_flat_path(flat)%></div>
          <div class="card-delete" style="z-index:999;"><%= link_to ("<i class='fa fa-trash'></i>").html_safe, flat_path(flat), method: :delete %></div>
          <%end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>