config/routes.rb
Rails.application.routes.draw do

  root to: 'flats#index'
  get 'flats/search'

  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks'}

  resources :flats do
    resources :bookings, except: [:destroy]
    resources :images, only: [:new, :create, :destroy]
  end

  resources :users, only: [:show]

end

app/models/image.rb
class Image < ActiveRecord::Base

  belongs_to :flat

  mount_uploader :photo, PhotoUploader

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def new
    @flat = Flat.find(params[:flat_id])
    @image = Image.new
  end

  def create
    @flat = Flat.find(params[:flat_id])
    @image = @flat.images.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to new_flat_image_path, notice: 'Image successfully added' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy


    redirect_to new_flat_image_path(@image.flat)

  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:photo)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/destroy.html.erb
<h1>Images#destroy</h1>
<p>Find me in app/views/images/destroy.html.erb</p>

app/views/images/new.html.erb
<%= form_for [@flat, @image]  do |f| %>

<div class="container" style="margin-top: 40px">
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :photo %>
    <%= f.hidden_field :photo_cache %>
  </div>
  <br>

  <div class="actions">
    <%= f.submit "Upload Image" %>
    <%= link_to "Finish Upload", flat_path(@flat), class: "btn btn-primary" %>
  </div>


  <div class="row" style="margin-top: 40px">
  <% @flat.images.each do |image| %>
    <div class="col-xs-12 col-md-6" style="margin-bottom: 40px">

    <%= cl_image_tag image.photo, height: 300, width: 400, crop: :fill  %>
    <div>
    <%= link_to ("<i class='fa fa-trash'></i>").html_safe, flat_image_path(image.flat_id, image), method: :delete %>
    </div>
    </div>
    <% end %>
  </div>

</div>

<% end %>